### PR TITLE
Adding facility to specify a location for results.

### PR DESCRIPTION
**Pull request by narasimhan-v**
Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by earlephilhower** [comment]
Howdy, thanks for the contribution.

I like this, but have one requested change.  The patch assumes the -o output directory already exists (which is not really the same as the default case where it makes the subdir transparently since $PWD already by definition exists):

[root@tm45 ezfio]# ./ezfio.py -o test123 -d /dev/loop0 -u 10
Unable to identify drive using sdparm. Continuing.
---------------------------------------------------------------------------
...
Please type the word "yes" and hit return to continue, or anything else to abort.
<yes>
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "./ezfio.py", line 873, in <module>
    SetupFiles()
  File "./ezfio.py", line 297, in SetupFiles
    os.mkdir(details)
OSError: [Errno 2] No such file or directory: 'test123/details_42GB_24cores_2500MHz_loop0_tm45.hgst.com_2016-08-15_10-45-00'

Can you replace "os.mkdir" on line 297 with "os.makedirs" which dies recursive directory creation?  That'll take care of this case as well.

We also need to add it to the Windows side as well, but since you're probably not running Windows on PPC I'll take a look at it myself after this merge.

Thx
-EFP3

**Comment by narasimhan-v** [comment]
@earlephilhower Done. Please check this.
Thanks :-)

**Comment by earlephilhower** [comment]
Ack, you hit the same problem I did when I tried the obvious.  There is no "os.mkdirs"   It's actually "os.*makedirs*".  They spelled out "make".  Got me, too!  Can you do one more try?

...snip...
Traceback (most recent call last):
  File "./ezfio.py", line 873, in <module>
    SetupFiles()
  File "./ezfio.py", line 297, in SetupFiles
    os.mkdirs(details)
AttributeError: 'module' object has no attribute 'mkdirs'

**Comment by narasimhan-v** [comment]
Oops, my bad. I did not check too.
Will send another commit on same PR ?

**Comment by earlephilhower** [comment]
Yes, please.  They can all be squashed while merging so just commit and push to your repo and it will show up here automatically.

**Comment by narasimhan-v** [comment]
Done. Thanks

**Comment by earlephilhower** [comment]
One more problem, unfortunately.  The ODS file is assumed to be in the directory you're writing to, so it also fails.  The error occurs here:
>    odssrc = outputDest + "/original.ods"

It *should* be:
>    odssrc =  os.getcwd() + "/original.ods"

So it'll take the original.ods file from the execution directory.

...
Sustained Multi-Threaded Random Write Tests by Block Size, BS=131072    2,223.25    17,786  11107.9
Traceback (most recent call last):
  File "./ezfio.py", line 876, in <module>
    GenerateResultODS()
  File "./ezfio.py", line 814, in GenerateResultODS
    xmlsrc = GetContentXMLFromODS( odssrc )
  File "./ezfio.py", line 738, in GetContentXMLFromODS
    ziparchive = zipfile.ZipFile( odssrc )
  File "/usr/lib64/python2.7/zipfile.py", line 752, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'test123/original.ods'

**Comment by narasimhan-v** [comment]
Done. And verified that it works.

**Comment by earlephilhower** [comment]
Merged.  Thanks!

**Comment by narasimhan-v** [comment]
Thanks

**Pull request merged**
